### ISSUE TITLE
Kerékelfordulás kontextusba helyezése

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2017-Osz/AutomatedCar#140]
Jelenleg a [-1,-1] (?) valós intervallumon állítjátok be a kerék elfordulását. Ez mértékegység nélkül értelmezhetetlen, legyen helyette egy [-50°, 50°] intervallum.

**Comment by Norbotwastaken** [comment]
[-60°, 60°] az uj intervallum, double [-0.6 ; 0.6]
