### ISSUE TITLE
Interface egyeztetése...

### ISSUE THREAD

**Issue by danijanos** [SzFMV2017-Osz/AutomatedCar#15]
Elfogadható-e számotokra az a megvalósítási mód, ha létrehozunk egy singleton osztályt az adattagoknak és e fölé ki-ki definiálhatja a maga interface-ét?
pl: private int accPedalPosition; public int getAccPedalPosition();

**Comment by danijanos** [comment]
Szia! Működhet a dolog, bár én támogatom egy olyan közös virtuális busz használatát, amin mozognak a jelek, mint például a gázadás vagy épp a kormány elfordítása...és hogy az lenne egy singleton, ahogy ez a referencia architektúrán látszik. De beszéljünk még róla :)

**Comment by danielvertesi** [comment]
Szia! Bármelyiket is használjuk,lassan lehet valahogy fel kellene osztani a feladatok,hogy ki mit csináljon.

**Comment by pintergreg** [comment]
Látom halad a munka, annyit javasolnék, hogy ha van érintett csapat, akkor legyen hivatkozva, pl. @SzFMV2017-Osz/team8 a váltás miatt, vagy @SzFMV2017-Osz/team3 a kormányzás miatt, hogy kapjanak értesítést.

Szintén javaslat, hogy ha egy függőségben levő másik csapat (éppen) inaktívnak tűnik, nem tilos, sőt már-már javasolható megoldást ajánlani. A gáz-fék esetében a feladatban rögzített 0-100 skála van, ezen nincs mit nagyon vitatni interfész szerűen, és -erről lesz még szó holnap- de a timer-es megoldás sem nagyon kérdés már, mert közben eldöntöttük, hogy ezt szeretnénk látni.
Nem specifikáltuk továbbra sem a kormánypozíció leírását, erre (egy ilyen helyzetben) célszerű a *nektek legkényelmesebb* (gyakorlatilag legegyszerűbb) megoldást propagálni a másik érintett csapat felé. Ha nekik nem felel meg, akkor jelzik.

**Comment by gacsibeni** [comment]
Elnézést, volt egy mellékattintás.
Kérdésem lenne Team6 részről (műszerfal), hogy nekünk közvetlenül a buszra menő jelek alapján kellene jeleznünk az elemek aktuális állapotát, vagy inkább az egyes buszjeleket kezelő alrendszerek felől vegyük az információt?

**Comment by pintergreg** [comment]
Buszról kellene venni minden adatot, az autó összes belső állapota a buszon keresztül kell, hogy elérhető legyen. Így a váltó, sebesség és fordulatszám is. Ami a buszra van kiírva azt kell megjeleníteni.
