### ISSUE TITLE
WorldObject osztály x,y pozíció koordináták Vector2D típusra cserélése

### ISSUE THREAD

**Issue by K987** [SzFMV2017-Osz/AutomatedCar#152]
- [ ] x,y pozíció koordináták Vector2D-re cserélése a WorldObjectben
- [ ] Indukált változások végig vezetése az osztály modellen
- [ ] Builder oszályok és WorldObjectFactory módosítása
- [ ] xml parseolás során a pixel pozicíó méterre konvertálása
- [ ] A vektorok x és y koordinátáinak közvetlen beállítására ne legyen lehetőség (pl elkerülendő a fák mozgatása...)

**Comment by JohnReynold** [comment]
> x,y pozíció koordináták Vector2D-re cserélése a WorldObjectben

Javaslom hogy a getX/Y-t hagyjátok bent és legyen @Deprecated de működő. Vizualizáció nagyon sok helyen használja. Vagy az, vagy átkövethetitek a visualisation osztályain is a változást.

**Comment by hazaip** [comment]
Lehetne azt is csinálni, hogy a getX/Y továbbra is működik, de az alap
tárolás Vector2D-ben lenne, amit getPosition-nel lehet elérni, valamint a
getX/Y-ra lenne 2 overload, az egyik intet másik double-t ad vissza, így a
vizualizációnak semmit nem kellene refaktorálnia, viszont az npc és az ego
car meghajtások Vector2D alapúak lennének.

2017. október 21. 13:19 JohnReynold írta, <notifications@github.com>:
