### ISSUE TITLE
Buffered image létrehozás a worldObjectben

### ISSUE THREAD

**Issue by K987** [SzFMV2017-Osz/AutomatedCar#153]
- [ ] resourceból visszakapott képfájlnév alapján bufferedImage létrehozása a WorldObjectben
- [ ] kép mérete alapján az objektum szélességének és hosszának meghatározása 1:1-ben
- [ ] szélesség és magasság tárolása méterben lebegőpontos típusban

**ÚJ:**
- [ ] getShape() metódus a WorldObjectben adja vissza az objektumot reprezentáló shape-t (pozíció, dimenzió, forgatás, ...)

**Comment by JohnReynold** [comment]
Nem kell, mert már van rá memóriatakarékosabb megoldás a vizualizációnál (nem minden objektumnak van saját Image-e, csak annyi Image példány van ahány *fajta* fájl van).
