### ISSUE TITLE
Detektálhatóságot garantáló interfész "család" tervezése

### ISSUE THREAD

**Issue by K987** [SzFMV2017-Osz/AutomatedCar#155]
a tervezés során a következőket kell figyelembe venni:

- [x] 1 szenzorhoz 1 db interfész típust kell tervezni
- [x] Az interfész garantálja azokat a szolgáltatásokat, amelyeken keresztül a szenzor a számára érzékelhető összes releváns információt lekérheti a detektált objektumról
- [x] amennyiben lehetséges és releváns, az interfészek legyenek hierarchiába szervezve (ha az elősegíti az áttekinthetőbb felhasználást/implementációt)
- [x] a tervezés során meg kell vizsgálni, hogy világ mely elemeinek kell az 1-1 interfészt megvalósítania. Ha szükséges az adott világ elem tervét bővíteni kell további tulajdonságokkal (tagváltozók, metódusok, absztrakt metódusok, ...).
- [x] a fentiekből egy elsőkörben osztály diagramot kell készíteni és prezentálni a csapatoknak.

**Comment by ebquhf** [comment]
![image](https://user-images.githubusercontent.com/18901815/32019757-80bc98a4-b9ce-11e7-9df5-dda27e122bc5.png)


Felvettem a 3 szenzorhoz szükséges interfészt a diagramba, behúztam melyik osztály valósitja meg azt is.
Az ISensor az ultrahangos szenzor által érzékelhető objektum ez csak egy távolságot ad vissza, illetve ebből származk a másik két szenzortípushoz tartozó interfész.
Az IRadarSensor a távolságon felül egy sebesség vektort ad vissza.
Az ICameraSensor visszaad egy forgatási szöget, a tábla/út típusát illetve magát az érzékelt táblát/utat WorldObjectként.

**Comment by K987** [comment]
@ebquhf Most nézem hogy a Radar szenzor nem fogja látni azokat az objektumokat, amiknek neki lehet menni, csak azok, amik mozognak. Ez így szerintem nem jó
