### ISSUE TITLE
Ütközés detektálás rendszer tervezése

### ISSUE THREAD

**Issue by hazaip** [SzFMV2017-Osz/AutomatedCar#163]

**Comment by danijanos** [comment]
A Team 4 User story 2 (#148) -ből kiindulva és megbeszéltek alapján, szerintem a CollidableObject abstract osztály doOnCollision abstract metódusát kéne

utput: esemény kiváltása ütközések bekövetkezésekor (ez írja le, hogy mik ütköztek); új mozgásállapot minden mozgó, ütköző objektumnak

A vezérelt autó - tereptárgy ütközésének detektálása és esemény kiváltása
 A vezérelt autó - NPC-vel való ütk

**Comment by danijanos** [comment]
A Team 4 User story 2-ből (#148) plusz az órán megbeszéltek alapján, szerintem a CollidableObject abstract osztály doOnCollision abstract függvényét kéne implementálnunk.

Valamelyik csapat készített egy WorldObjectCollection osztályt, ahol leválogatták a különböző világ objektumokat unmoving, moving, collidable és cars típusokra. Mindegyik listára van egy publikus getterük is. Szerintem ezt érdemes lenne használnunk.

Tehát végigiterálnánk ezeken a listákon, és megvizsgálhatnánk, hogy a koordinátáik nem "fedik"-e a vezérelt WorldObject típusú playerCar példány épp aktuális koordinátáit.

Ha igen, akkor álljon meg, érjen véget a játék - és ezt szerintem a vizualizációs csapat Dashboard osztályát felhasználva kéne valahogy beépíteni a szimulációba

és ezekre kéne pár teszt első körben.
