### ISSUE TITLE
Ütközés detektáló függvény megvalósítása

### ISSUE THREAD

**Issue by hazaip** [SzFMV2017-Osz/AutomatedCar#166]

**Comment by danijanos** [comment]
@SzFMV2017-Osz/everyone 
Kicsit meg vagyok akadva azzal, illetve nem igazán értem, hogy a AutomatedCar osztály miért nem CollidableObject leszármazott?

https://github.com/SzFMV2017-Osz/AutomatedCar/blob/fe129ec5c463109c08321929e9501ed4cf41f422/src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java#L11

tudna ebben bárki, aki részt vett a tervezésében segíteni vagy megvilágítani, hogy ez miért van így?
köszi :v:

**Comment by K987** [comment]
lásd #179

**Comment by danijanos** [comment]
ezaz igen... ahogy nézem arra sem jött semmi reakció :interrobang: így nem vagyunk előrébb, de akkor lehet, hogy csinálok egy változtatást ezzel.
