### ISSUE TITLE
fewfgewggewg

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2017-Osz/AutomatedCar#167]
@SzFMV2017-Osz/everyone Ha valaki tud valamit a fent nevezett kollégáról, akkor kérem, hogy jelezze, mert több szempontból is érdekes ez.
Igazából a @SzFMV2017-Osz/team5 tagjának tűnik [a commit-ok alapján](https://github.com/SzFMV2017-Osz/AutomatedCar/commits?author=fewfgewggewg).

**Comment by fandras32** [comment]
A csapatkapitányunk által felküldött commit-ok jelennek meg ilyen névvel, valószínűleg program beállítási hiba miatt.

**Comment by pintergreg** [comment]
Oké köszönöm.
