### ISSUE TITLE
Nincs végigkövetve a világmodell változása a kódon

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2017-Osz/AutomatedCar#17]
Nem fordul a kódotok a kezdetleges világmodell módosításai végett. 
https://travis-ci.org/SzFMV2017-Osz/AutomatedCar/builds/280383186

**Comment by K987** [comment]
@SzFMV2017-Osz/team1  valaki majd review-za, hogy végig menjen a pull. tnx

**Comment by K987** [comment]
@SzFMV2017-Osz/team1 Valaki review-zná pls!!??
#32

**Comment by mezakos** [comment]
@SzFMV2017-Osz/team1 BufferedImage tárolása kéne a WorldObject osztályban
