### ISSUE TITLE
Motorfékkel nem csökken nullára a sebesség

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2017-Osz/AutomatedCar#174]
Az alapjárat 600 rpm, ami alá nem csökken a fordulatszám, ez rendben van, de az autó sebessége sehogyan nem megy 6km/h alá (műszerfalról leolvasott érték), ha átteszem hátramentbe, akkor hirtelen -km/h-ra ugyrik ás hátrefele kezd haladni, ha előremenetbe teszem, akkor -6-ról 6-ra ugyrik...
Az autó sebessége nullára lassuljon, ha nincs gyorsító erő. Ha a motor eléri az alapjáratot és főleg ha üresbe teszem, tehát a kerekekre nem adot nyomatékot, akkor nulláig kellene lassulnia az autónak.

**Comment by pintergreg** [comment]
@SzFMV2017-Osz/team8 Ja igen, ezt a master állapota alapján van most így.

**Comment by self-driven** [comment]
A motorfék csak az alapjárati fordulatszámnak megfelelő sebesség eléréséig fékez.
Környezeti fékező hatás nincs implementálva, a váltót üresbe kapcsolva egyáltalán nem fog lassulni az autó. Nem emlékszem olyasmire, hogy surlódásnak vagy menetszél fékező hatásának érvényesítése a feladat része lett volna.

**Comment by pintergreg** [comment]
Ha nagyon szőrözni akarok, akkor de. Viszont jelenleg van épp elég teljesíteni való feladat ami fontosabb ennél.

> Az autónak egy leegyszerűsített modellen keresztül ugyan, de mégis valóságosan kell viselkednie, ehhez pedig megfelelő fizikát kell leprogramozni. Az haladásához nyilván sebességre lesz szükség, amit a motorerő gyorsító ereje segítségével kaphatunk, és ami a gázpedál(t helyettesítő billentyű) elengedésével nem szűnik meg azonnal, tehát ha úgy tetszik lendületben marad, **viszont a környezet (légellenállás, súrlódás) fokozatosan fékezi**. Nem kell az egész univerzumot szimulálni, de legalább egy gyorsító és egy fékező erő például biztosan szükséges lesz.
[Fizika](https://github.com/SzFMV2017-Osz/AutomatedCar/wiki/Fizika)

**Comment by pintergreg** [comment]
A 3. sprintben lehet, hogy jól jön majd pár csapatnak, szóval wontfix-re tettem.
