### ISSUE TITLE
WorldObject.getShape() mindig egy üres Polygon példánnyal tér vissza

### ISSUE THREAD

**Issue by danijanos** [SzFMV2017-Osz/AutomatedCar#210]
Sziasztok @SzFMV2017-Osz/team1 !

Az a problémám, hogy a Collision Detection tesztjeim elhasalnak, mióta az új WorldObject-ben implementált getShape() metódussal próbálom a különböző világelemeket ütköztetni az autóval a szintén általatok kitalált és javasolt alábbi módszerrel:

https://github.com/SzFMV2017-Osz/AutomatedCar/blob/96f63ee9adda0ac19ddd611c12075b5a8c05f019/src/main/java/hu/oe/nik/szfmv/environment/detector/CollisionDetection.java#L10-L15

végig F7-eztem a hívásláncot és nekem ez a sor gyanús:

https://github.com/SzFMV2017-Osz/AutomatedCar/blob/96f63ee9adda0ac19ddd611c12075b5a8c05f019/src/main/java/hu/oe/nik/szfmv/environment/model/WorldObject.java#L158

nem lehet, hogy ott hiányzik egy felkiáltójel?

```
while (!pathIterator.isDone()) { 
```

nem ismerem nagyon a működést, de ha tudtok segíteni egy gyors fixel, azt megköszönném,
persze az is lehet, hogy totál félreértem az egészet, csak most nincs sok időm, hogy szöszöljek vele.

Köszi!

**Comment by K987** [comment]
#211 pr-ben a javítva
