### ISSUE TITLE
Szenzorok vizualizációjának ki/be kapcsolása

### ISSUE THREAD

**Issue by danijanos** [SzFMV2017-Osz/AutomatedCar#220]
Sziasztok @SzFMV2017-Osz/team5 !

Első kérdésem az lenne, hogy olvastam a sprint 2-re vonatkozó DoD-teket és jól értem, hogy mindegyik szenzort (kamera, radar, ultrahang) külön gombbal kéne kapcsolni?
ha igen, megfelel-e ez nektek így:
- 1 gomb => kamera
- 2 gomb => radar
- 3 gomb => ultrahang

vagy mindegyik enum típusra legyen egy ki-bekapcsoló gomb?

CAMERA, RADAR, ULTRASONIC_FR, ULTRASONIC_FL, ULTRASONIC_RL, ULTRASONIC_RR,ULTRASONIC_LSF, ULTRASONIC_LSB, ULTRASONIC_RSF, ULTRASONIC_RSB

a másik kérdésem pedig, hogy ezt úgy kéne megvalósítanunk, hogy a pull requestetekben lévő GameDisplayJPanel.java állományban a setereket használjuk?

```
     public void setCameraSensorDebugMode(boolean cameraSensorDebugMode) {
         this.cameraSensorDebugMode = cameraSensorDebugMode;
     }

     public void setRadarSensorDebugMode(boolean radarSensorDebugMode) {
         this.radarSensorDebugMode = radarSensorDebugMode;
     }
 
     public void setSensorSensorDebugMode(boolean sensorSensorDebugMode) {
         this.sensorSensorDebugMode = sensorSensorDebugMode;
     }
```

vagy írjunk elő egy interfészt, amin keresztül tudunk kommunikálni? (boolokat billentgetni? :stuck_out_tongue_winking_eye: )

**Comment by fandras32** [comment]
Igen, nagyjából jól érted. Annyi, hogy az általad is írt 1-2-3 gombokon kívül, lenne egy 0-ás gomb is (sprint2-nk szövege alapján), ami egyben kapcsolgatja, hogy egyáltalán debug módban vagyunk-e, vagy sem (a többihez hasonló setSensorDebugMode nevű metódus jelenleg). Ha nem ragaszkodtok az interfészes megoldáshoz, kicsit módosítanám a mostani metódusainkat úgy, hogy Nálatok már ne kelljen vizsgálni, hogy épp ki vagy be van kapcsolva egy adott szenzor, Ti csak a pl 1-es gombnyomásra meghívnátok egy paraméter nélküli függvényt, ami a mi részünkön csekkolja, hogy a kamera milyen állapotú, és azt az ellenkezőjére billenti.
Ezek lennének pl:
- changeCameraSensorDebugMode()
- changeRadarSensorDebugMode()
- changeSensorSensorDebugMode()
- changeSensorDebugMode()

**Comment by fandras32** [comment]
Felpusholtam egy változtatást a "Team5_Sensors_Demo2_merge_with_master"-be az alapján, ahogy én gondoltam ezt az egészet. Review-old légyszi, hogy részetekről ez így oké-e. A UserInputHandler.java fájlotok a billentyű lenyomás vizsgálataitok végére a 0-3ig számokat beírtam.

**Comment by danijanos** [comment]
@fandras32 én első körben nem is akartam nagyon csekkolni semmit, csak simán így meghívni a függvényeteket:
```
gameDisplayJPanel.setCameraSensorDebugMode(!gameDisplayJPanel.isCameraSensorDebugMode());
```
magyarul akármit ad vissza az adott bool mező gettere, azt negálva adom át paraméterként az adott field setterének... vagy az nagyon pronyó így? tudom nincs sok null exception check meg hasonló fancy dolgok, de legalább [KISS](https://en.wikipedia.org/wiki/KISS_principle) :raised_hands:

**Comment by fandras32** [comment]
Elvileg úgy is ment volna, de talán így change-ekkel szebb.
