### ISSUE TITLE
Elérhetőségek

### ISSUE THREAD

**Issue by vkrisztian** [SzFMV2017-Osz/AutomatedCar#25]
Megkérném azt a 2 embert aki külön csapódott hozzánk, hogy legyen szíves valami olyan elérhetőséget adni (pl. skype), ahol megbeszélhetnénk a dolgokat.

**Comment by pintergreg** [comment]
@vargarobi93 és @hazaip 
Már akartam kérdezni, hogy sikerült-e kommunikációs csatornát találni.

**Comment by vargarobi93** [comment]
Facebook-on is beszélhetünk (megtaláltok "Varga Róbert" néven, több NIK-es csoportban is benne vagyok).
Skype-on a "vargarobi93@hotmail.com" címen lehet elérni, de azt előre beszéljük meg itt vagy facebook-on, mert a Skype-ot ritkán nézem.

**Comment by hazaip** [comment]
Skype: peet3d
gmail: hpeet3d@gmail.com

facebookom nincs

**Comment by hazaip** [comment]
Ti is megadhatnátok akkor ide a tietekét, skype lesz a nyerő szerintem.

**Comment by JohnReynold** [comment]
Skype: miskolczi.kristof
