### ISSUE TITLE
Kérdés:

### ISSUE THREAD

**Issue by gacsibeni** [SzFMV2017-Osz/AutomatedCar#33]
IntelliJ-ben hogyan kell felkonfigurálni a run beálltásokat, hogy futtatható legyen a kód?

**Comment by pintergreg** [comment]
A projektet maven projektként kell importálni, ezután futtathatónak kellene lennie. Mi a gond?

**Comment by gacsibeni** [comment]
Köszönöm, a probléma az volt, hogy nem Maven projectként volt importálva.
