### ISSUE TITLE
IMovable interface definiálása

### ISSUE THREAD

**Issue by vkrisztian** [SzFMV2017-Osz/AutomatedCar#35]

**Comment by hazaip** [comment]
Felmerült bennem a kérdés hogy nem akarja esetleg a hajtás lánc illetve kormányzás ezt az interfacet használni. Ki fogom egészíteni pár dologgal, pl addForce(), addRadialForce() (utóbbi a kanyarodáskor a fordulást megvalósítandó), illetve bevezetnék csillapítást is (pl. motorfék,vagy a kormány ahogy vissza áll középre magától az autó újra egyenesen megy). 
A hajtásnak ill kormányzásnak ezeket a metódusokat kellene implementálni, mikor mekkora erőt kell átadni, és a move metódus pedig az aktuális erő hatások erdője alapján számolja ki az új pozíciót, elfordulást minden framen. Kíváncsi vagyok az érintett csapatok véleményére.

**Comment by szum7** [comment]
Ha jól gyanítom, akkor ez az IMovable egy, az NPC-k mozgatását definiáló interface lenne. 
Amennyire eddig látom, NPC objektumok és az autó mozgása eléggé el fog térni egymástól és azok a metódusok, amiket megneveztél, inkább a kormányzásért felelős csapatra @SzFMV2017-Osz/team3 és ránk, a hajtáslánc csapatra @SzFMV2017-Osz/team8 tartozik. A motorfék például konkrétan egy olyan paraméter, amit számolnunk kell és továbbítani a műszerfalnak.

**Comment by hazaip** [comment]
Igen ennek indult, de mivel a mozgatás végeredménye az egocar esetében is hasonló, ezért lehetne ugyanazt az interface-t használni mindkét esetben, erre vonatkozott a felvetésem.
Ezeket a számításokat továbbra is implementálnotok kell, ez csak egy interface, ami lehetővé teszi a kommunikációt az objectek és a világ között.

**Comment by szum7** [comment]
Sokat gondolkodtunk ezen a kérdésen, és arra jutottunk, hogy a mi munkánk szempontjából nincs szükség egy ilyen interfacere. Mi a PowertrainSystem-el dolgoztunk, az autóval, mint megjelenítendő objektummal nem.
Ha azt mondod, hogy nektek szükségetek van rá, hogy az AutomatedCar megvalósítson egy interface-t, és az ránk hatással lenne, akkor kérnénk egy pontosabb javaslatot (lehetőleg kódot), hogyan nézne ki ez az IMovable interface.
