### ISSUE TITLE
TDD

### ISSUE THREAD

**Issue by danijanos** [SzFMV2017-Osz/AutomatedCar#40]
Azt szeretném kérdezni @pintergreg -től, hogy a fejlesztés minden zöld fázisát kommitoljuk vagy csak az úgymond final végterméket?

**Comment by pintergreg** [comment]
Talán a legjobb kifejezés, hogy a logikailag egybefüggő változtatásokat célszerű egy commit-ban összefogni. Ez lehet egy bugfix, ami mondjuk 1 karaktert érint, vagy lehet egy refaktor (pl. metódusátnevezés), ami 28 fájlt. De igazából a TDD a kérdés, szerintem ha pl. van egy feladat, ami 3 részből áll (3 elem van a DoD listában), akkor mindnek mehet egy-egy commit, viszont egy-egy elem teljesítése a TDD mikrociklus akár többszöri lefutását is eredményezheti, amiket külön-külön szerintem fölösleges.
A „sok” commit nem gond, a túl kevés viszont az tud lenni, ha pl. utólag kell hibát felkutatni, és arra sikerül leszűkíteni, hogy az xy committal került be, de az jól láthatóan sok különböző célú változtatást tartalmaz, akkor nem lehet könnyen megmondani, hogy melyik okozhatta a gondot.
Remélem sikerült megválaszolni a kérdést. :)

**Comment by danijanos** [comment]
igen, köszönöm! :)
