### ISSUE TITLE
Team8 munkamenet kialakítása

### ISSUE THREAD

**Issue by szum7** [SzFMV2017-Osz/AutomatedCar#42]
Mivel a csapat nagy részének (ha nem mindenkinek(?)) új ez a githubos közös munka, ki kéne alakítanunk, ki hogyan dolgozik, hogyan commitolunk, tartunk review-t, stb.

Ezt a kialakítást egy egyszerű java metódus (egy getter pl. vagy akármilyen egyszerű kódrészlet) végigkövetésén fogjuk elvégezni.

**Comment by pintergreg** [comment]
@SzFMV2017-Osz/team8 Van valami technikai probléma, amit hátráltat, vagy csak annyi, hogy még szokatlan?
Javasolt olvasnivaló: 
* [wiki/GitHub](https://github.com/SzFMV2017-Osz/AutomatedCar/wiki/GitHub)
* [wiki/Munkafolyamat](https://github.com/SzFMV2017-Osz/AutomatedCar/wiki/Munkafolyamat)

**Comment by szum7** [comment]
@pintergreg Még nincs probléma, egyelőre csak egyeztetünk csapatilag egy megbeszélést.
