### ISSUE TITLE
Egyeztetés a PowertrainSystem szerepéről

### ISSUE THREAD

**Issue by szum7** [SzFMV2017-Osz/AutomatedCar#44]
A 2017. 10. 05.-ei órán a @SzFMV2017-Osz/team4 felvetett egy másfajta értesítési rendszert, mint a mostani PowertrainSystem. Ezt kellene itt megbeszélnünk, hogy mire gondoltak, mert az órán nem sikerült megállapodni, hogy mi legyen.

Amennyire sikerült értelmeznünk, a javaslatotok sokat változtatna a jelenlegi szerkezeten, amire mi már építünk - így nem szeretnénk váltani. De egyeztetés nélkül se szeretnénk hagyni a dolgot.

szum7
@SzFMV2017-Osz/team8 (Hajtáslánc)

**Comment by danijanos** [comment]
Szia!

Már tegnap szerettem volna írni én is egy VBV, azaz VitrualBus vita nevű issue-t, de megelőztél :)
Ott maradtunk páran még fél órát elmélkedni erről @pintergreg -el és @usanyo -val és a @SzFMV2017-Osz/team4 pár tagjával, és arra jutottunk, hogy akkor nem variálok becsomagoljuk Signal-okba az átszámolt keyEventeket és ráküldjük nektek a VB-re hogy mindenki boldog legyen.

Arra gondoltunk, hogy mi így foglalnánk le az ID-ket

- 101 => gázpedál állása
- 201 => kormány állása
- 301 => sebességváltó állása

a köztes számokat, pl 102, 103 és társai , az NPC cuccok vihetik.

A Signal Object típusú data fieldjében pedig

- gázpedál => int | range: (0) - (+100)
- kormány => int | range: (-100) - (+100)
- sebességváltó => String | ["P", "R", "N", "D"]  (ez lehet Char is, ha úgy valamiért könnyebb)

okés így?

**Comment by szum7** [comment]
Ahol lehet érdemes lenne enumot használni.
- A sebességváltó fokozatai mindenképp enum legyen (AutoTransmissionEnum P,R,N,D)
- Mivel a signal típusok is végesek és jól meghatározhatóak, az int típusú "id"-t le lehetne cserélni SignalEnum típusra (GASPEDAL, BREAKPEDAL, STEERINGWHEEL, AUTOTRANSMISSION, stb.) Ehhez persze nem ragaszkodunk, ha valamiért mégis előnyösebb lenne integerként.

Többi ponttal egyetértünk, schuper lesz.

**Comment by eky0151** [comment]
Enum-mal szerintem is jobb lenne, meg átláthatóbb

**Comment by danijanos** [comment]
@szum7 ok!
