### ISSUE TITLE
Enum-ok

### ISSUE THREAD

**Issue by danijanos** [SzFMV2017-Osz/AutomatedCar#45]
@SzFMV2017-Osz/team8 hoz írok elsősorban, de talán mindenkinek hasznos lehet, hogy ha olyan enumokat találunk ki, amit másnak is használnia kell majd a csapaton kívül, és amíg nincs a kódotok a masterbe mergelve, illetve hogy nem kelljen brancheket checkoutolni vagy itt bogarászni egymásét, szerintem hasznos és gyors megoldás lenne ide kigyűjteni és ha kell updatelni ezeket.

... csak mert látom, hogy nálatok(team8) már vannak ilyen típusok, miközben én is ilyeneket írok éppen :)

**Comment by szum7** [comment]
Teljesen egyetértek, hogy egyeztetni kéne. Mi ezeket az enumokat definiáltuk:

_AutomatedCar/src/main/java/hu/oe/nik/szfmv/automatedcar/bus/SignalEnum.java_
```
public enum SignalEnum {
    GASPEDAL, BREAKPEDAL, STEERINGWHEEL, AUTOTRANSMISSION, REVOLUTION, SPEED
}
```
_AutomatedCar/src/main/java/hu/oe/nik/szfmv/automatedcar/bus/AutoTransmissionEnum.java_
```
public enum AutoTransmissionEnum {
	P, // parkolás
	R, // hátra
	N, // üres
	D // előremenet
}
```

**Comment by danijanos** [comment]
@szum7 ha megengedsz egy megjegyzést, én azt javasolnám, hogy egy kicsit módosítsunk az elnevezéseken.
Ahogy azt a #44 issue-ban már megbeszéltük, mi is rádobjuk a user által nyomott billentyűket, mint Signalokat a VB-ra. Láttam, hogy ebben: 5088826 a commitban a Signal class-t is átírtátok, hogy legyen SiganlEnum tipusú mezője. Azt érzem zavarónak, hogy, ha mi rádobunk pl egy ilyet, hogy:
```
new Signal(SignalEnum.GASPEDAL, this.currentGaspedalState);
```
,akkor amikor ezt valaki le-swichcase-eli (ezzel a gyönyörű magyar szóval), akkor mire gondoljon, hogy ez most a gazpedál mije? Lehet, hogy ez szőrszálhasogatásnak hangzik, de ha már clean codot próbálunk írni én azt javaslom, hogy:
```
public enum CarComponentState{
GASPEDAL,
BRAKEPEDAL,
STEERINGWHEEL, 
GEARSHIFT
}
```
A REVOLUTION és SPEED -ről nem nyilatkozom, mert az nem tartozik ránk. csak ugye így meg több enum kéne. Akkor meg a Signal class-t kéne megbonyolítani. Szóval lehet, hogy az egész enumozásnak ilyen szempontból nem nagy haszna van. Mármint ezek csak konstansok... nem tudom.
Az AutoTransmissionEnum-nak sem látom most így elsőre sok értelmét, de biztos tudsz valamit, amit én nem :)

@SzFMV2017-Osz/team6 , nektek kell gondolom a v.buszról leszedni majd ezeket, ott mi a vélemény erről?

**Comment by danijanos** [comment]
vagy akkor azt mondom, hogy:
```
public enum CarComponentState {
    GASPEDAL      (101),
    BRAKEPEDAL    (102),
    STEERINGWHEEL (103),
    GEARSHIFT     (104)
    ;

    private final int carComponentStateID;

    private CarComponentState(int ID) {
        this.carComponentStateID = ID;
    }

    public int getCarComponentStateID(){
        return this.carComponentStateID;
    }
}
```
és így a Signal osztályt sem kell buzergálni:
```
CarComponent gearShift = CarComponent.GEARSHIFT;
VirtualFunctionBus.sendSignal(new Signal(gearShift.getCarComponentID(), this.gearShiftState));
```
mit szóltok?

**Comment by danijanos** [comment]
illetve hülye vagyok, tök fölösleges helyi változó belőle:
```
            VirtualFunctionBus.sendSignal(
                    new Signal(
                            CarComponent.GEARSHIFT.getCarComponentID(),
                            this.gearShiftState
                    )
            );
```

**Comment by self-driven** [comment]
Az elején mi is így futottunk neki, hogy kapott egy lekérdezhető int mezőt az enum, de származik-e ebből bármiféle előny egyáltalán, valamint minden esetben hosszabbá válik a componensekre való hivatkozás és egy egyszerű switch közvetlenül el sem fogadja a lekérdezett id értéket, mert konstansokat vár.

Pl. ez nem műxik:
int cc = CarComponent.BRAKEPEDAL.getCarComponentID();
switch (cc) {
       case CarComponent.BRAKEPEDAL.getCarComponentID():
       break;
default:
	break;
}
Szerintem nincs szükségünk rá, hogy az enumot egy plusz int mezővel is megfűszerezzük. Az enum elnevezése tőlem lehetne más, de pl. egy sebesség signal-ra nem igazán illik a CarComponent elnevezés.

**Comment by szum7** [comment]
Ezt nem teljesen értem:
"Azt érzem zavarónak, hogy, ha mi rádobunk pl egy ilyet, hogy:

`new Signal(SignalEnum.GASPEDAL, this.currentGaspedalState);`

,akkor amikor ezt valaki le-swichcase-eli (ezzel a gyönyörű magyar szóval), akkor mire gondoljon, hogy ez most a gazpedál mije?"

A SignalEnum a Signal típusa. A felhozott példában ez egy gázpedál típusú szignál. Ha switchelni akarsz, akkor abban megvizsgálod, hogy milyen típusú szignállal van dolgod. Nem?

**Comment by danijanos** [comment]
@self-driven szerintem valahogy így lehet le-switchelni pl:
```
@Override
    public void receiveSignal(Signal s) {
        CarComponent CCID = CarComponent.values()[s.getId()];         
        switch (CCID){
            case GEARSHIFT:
                this.gearShiftState = (String)s.getData();
                break;

            default:
        }
    }
```
előny annyi származik ebből, hogy nincs senki ahhoz kötve, hogy ha rá akar tenni egy jelet a buszra, akkor csak egy bizonyos enum típust használhat. Így mindenki relatív függetlenül fejleszthet magának enumokat. Azt kell csak figyelembe venni, hogy ne legyen ID ütközés.
A sebesség signal lehet egy teljesen más enum csomagban, pl CarMotionStateProperty
Az kétségtelen, hogy hosszabbak lesznek hivatkozás nevek.

@szum7 nem azt írtam, hogy probléma van vele, hanem hogy zavaró. Azért írtam oda, hogy cleancode szempontból. Ha valaki mondjuk jövőre a mi kódunkból kiindulva szeretne fejleszteni (amit persze csak az elv szempontjából és teoretikusan értek), azzal találja magát szembe, hogy:
1. SignalEnum : az hogy valami enum az látszik a típusából, nem kell odaírni még egyszer
2. GASPEDAL : a gázpedál egy kocsi alkatrész, mi nem azt állítjuk, hogy ez egy x vagy y  típusú gázpedál, hanem a gázpedál helyzetének adunk új értéket, magyarul, hogy mennyire van benyomva. Ezt kérdezitek ti le és ebből számoltok majd fordulatszámot stb...

ezekért lenne talán egy fokkal értelmesebb szerintem a CarComponentState.GASPEDAL

Martin bácsi még valami olyasmit is mond, hogy ha egyben kiolvasod a kódot, amit írsz, az egy értelmes mondat legyen. Ha ez megvan, akkor közelíthetsz a CC felé.

Most úgy tűnhet, hogy én valami Clean Code náci vagyok, de egyrészt hidd el, hogy egy komolyabb munkahelyen, neadjisten multinacionális vállalatnál ezeket simán megkapod, sőt még durvábbakat is, másrészt itt kicsit szabadabban lehet gyakorolni az elveket, ha már ezt a tárgyat kábé ezért nevezik így, találták ki vagy legalább is ezért tanuljuk/ vettük fel...

**Comment by szum7** [comment]
Voltam/vagyok munkahelyen és ott tartjuk az MyNameEnum vagy MyNameType elnevezési konvenciót. Nem tudtam, hogy ez kiment a divatból.

Én még mindig logikusnak találom a SignalEnum elnevezést, egyértelműen jelzi, hogy ez a szignálok típusa. Milyen szignálról van szó? mySignal.id -> GASPEDAL.
A CarComponentState elnevezéssel azt veszem ki, mintha valahogy összekevernéd a logikát, és azt szeretnéd jelezni, hogy ez az enum milyen _érték_et kapott. Pedig az _érték_ (pl.: gázpedál->30%ig benyomva) a szignálhoz tartozik.

Itt példányosításnál is látszik, hogy a Signal-hoz tartozik az _érték_ - nem az enumhoz.

`Signal mySignal = new Signal(SignalEnum.GASPEDAL, value);`

`Signal mySignal = new Signal(CarComponentState.GASPEDAL, value);`

**Comment by gacsibeni** [comment]
Ennek itt végülis mi lett a megoldása? Mert jelenleg akkor most van a SignalEnum, ahol más intek jelentik a Gaspedalt stb. meg a CarComponent, ahol 101, 102 stb. az enumokhoz tartozó int érték.

**Comment by szum7** [comment]
A @SzFMV2017-Osz/team4 válaszát várjuk. (@danijanos)

**Comment by danijanos** [comment]
itt vagyok bocs.
@szum7

> Voltam/vagyok munkahelyen és ott tartjuk a MyNameEnum vagy MyNameType elnevezési konvenciót. Nem tudtam, hogy ez kiment a divatból.

én nem tudtam, hogy egyáltalán ez divatban volt. :) tényleg úgy írtok meg valamit, hogy class ValamiClass meg int ValamiInt ... O.o én soha nem láttam ilyen kódot, ha nagyon divatban lenne, akkor akár az egész Java architekutúrát is megírhatták volna így, pl hirtelen [itt egy Interface](https://docs.oracle.com/javase/7/docs/api/java/lang/Runnable.html), amit ti így írnátok le, hogy Interface RunnableInterface ? 
Na mindegy, most ez totál off topic, de azért meglepődtem.

A logikát biztos, hogy másképp értelmezzük.
tehát az enumok mire jók? mit akarok velük leírni, elérni?:
Enum => enumeration => felsorolás :: kvázi van egy szép névvel ellátott konstans listám
mit sorolok fel? 
CarComponent => autóalkatrészeket
mire használom a felsorolást?
arra, hogy azonosítsak vele egy Signal-t. (az érték mellette, csak ezt szolgálja, hogy ne kelljen átírnom a Signal class-t)

Értem én, hogy te Signal típusokat akarsz felsorolni, de a Signalnak már definiálva van egy típus(class).
Tehát én csak azt szeretném elérni, hogy egy Signalon belül, mi az, amit kapok, ha lekérdezem ID alapján a VB-ről.
magyarul mit kapszulál az adott Signal példány.
a te esetedben egy SignalEnum.GASPEDAL -t
nálam egy CarComponent.GASPEDAL -t

nekem a te logikád furcsa és nem értem, de látom, hogy ebből nem fogunk konszenzusra jutni, szóval én elengedem ezt, zárjuk rövidre, nem ezen fog elmenni a hajó.
Akkor legyen, ahogy ti akarjátok, és maradjon a bódogttá.

@gacsibeni -ék pedig nekiállhatnak annak, amit akarnak. Mi is átírjuk a megfelelő sorokat.

**Comment by szum7** [comment]
@danijanos 

> tényleg úgy írtok meg valamit, hogy class ValamiClass meg int ValamiInt ... 

Persze hogy nem. Az enumról beszéltem, nem tudom hogy jött szóba a class meg int. Enumnál _ValamiEnum_, ha már említetted az interface-t ott meg _IValami_. (A _Valami_ az elnevezés, pl.: IMovable) Osztályoknál nem jelezzük, hogy ...Class. Kérlek feltételezd jobban, hogy tudom miről beszélek.

Köszönjük, hogy mégis hajlotok a mi megvalósításunk felé. A következőt kéne mindenhol felhasználni:
```
public enum SignalEnum {
    GASPEDAL, BREAKPEDAL, STEERINGWHEEL, AUTOTRANSMISSION, REVOLUTION, SPEED
}
```
```
public class Signal {
    private SignalEnum id;

    public SignalEnum getId() {
        return id;
    }
   // ...osztály további leírása...
}
```
A _Signal_ osztály _id_ adattagja _int_ típusról _SignalEnum_ típusra változott. Kérlek ennek megfelelően változtassatok mindenhol a kódon. Valamint, ha szeretne valaki felvenni a SignalEnum-ba még értékeket, és úgy érzi, hogy nem teljes a lista (pl.: kéne neki egy SPONTANEOUSCOMBUSTION jeltípus), kérem itt jelezze!

**Comment by hazaip** [comment]
Off topic:
Ilyenkor, ha módosítok sokak által felhasznált valamit, pl ezt az enumot
jelen esetben, akkor a módosító felelőssége a használt kódokban is
módosítani azt, vagy commitolja be úgy, hogy biztosan nem működik a kód,
hiszen változtatás történt, és majd a felelős csapat javítja?

2017. október 13. 8:19 Áron Szőcs írta, <notifications@github.com>:

**Comment by szum7** [comment]
@hazaip 
Jó kérdés. Ez az issue egyelőre még csak egy felhívás, hogy számítsanak a csapatok arra, hogy ezt így csinálnánk, lehetőleg ők is így gondolkodjanak. A mergelés majd egy másik probléma lesz.
A @SzFMV2017-Osz/team3 és (nekünk) @SzFMV2017-Osz/team8 -nak biztosan szüksége van erre az egyeztetésre, jó lenne ha minden csapat elolvasná az issue-t, hogy használja-e a **Signal**okat.
(Egyébként ha valaki nem nyúlt a **PowertrainSystem**hez és nem is használt **Signal**okat, akkor nem lesz code conflict.)

**Comment by hazaip** [comment]
Nem is a code conflictra gondoltam, hanem ha pl megváltoztatok egy
interface szignatúrát az egy sor implementációs változtatást vonna maga
után, de azok már nem az én csapatom felelőssége mondjuk. A változtatás
következtében a kód nem fordul mert nincs implementálva sehol az új
interface rendesen. Ilyenkor nekem kell javítanom vagy commitoljam be
hibásan a kódot, vagy hogy kell ilyenkor eljárni?
A kérdés szól az oktatóknak is :)

2017. okt. 13. de. 8:49 ezt írta ("Áron Szőcs" <notifications@github.com>):

**Comment by danijanos** [comment]
@szum7 

> Az enumról beszéltem, nem tudom hogy jött szóba a class meg int.

azért raktam a kommentem elé, amit írtál, de akkor még egyszer:

> Voltam/vagyok munkahelyen és ott tartjuk a MyNameEnum vagy MyName**Type** elnevezési konvenciót.

szóval Type -ok: [egy](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), [két](https://docs.oracle.com/javase/tutorial/java/generics/types.html), [há](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/Type.html)

biztos vagyok benne, hogy tudod miről beszélsz, de ha már kérünk egymástól, kérlek nézd meg jobban mit írsz, vagy mit válaszolsz.
píísz.

**Comment by pintergreg** [comment]
@hazaip Egyértelműen a módosító felelőssége. Nem kerülhet be nem forduló kód már a csapat masterbe sem, de a masterbe meg pláne nem fogom elfogadni. Ha egy módosítás miatt nem fordul, mert egy másik csapat / kolléga kódjában is eszközölni kell a módosítást, akkor azt is meg kell csinálni. Ha egy teljes alrendszert érintene, akkor nyilván lehet vele konzultálni.

**Comment by szum7** [comment]
@danijanos 

> Voltam/vagyok munkahelyen és ott tartjuk a MyNameEnum vagy MyNameType elnevezési konvenciót.

Értsd: egy enumot mi úgy neveztünk el, hogy ValamiEnum vagy ValamiType. Ezt a két elnevezési konvenciót ismertem meg munkám kapcsán az enum témájában.

**Comment by danijanos** [comment]
valahogy majd azt is jelölnünk kéne szerintem, hogy hová, melyik package-be tegyük, tesszük a közös enumokat.
mondjuk pl ilyen un. permanent canonical url linkekkel:

https://github.com/SzFMV2017-Osz/AutomatedCar/blob/ab3935fda6ca309efb5acef1b48877f0985fff09/src/main/java/hu/oe/nik/szfmv/automatedcar/bus/SignalEnum.java#L1-L5

hogy ne legyen conflikt majd a végleges mergeléseknél az importok miatt... ne szívassuk meg nagyon @pintergreg -et se.

**Comment by hazaip** [comment]
Én írtam egy Vector2D osztályt, azt a common packagebe tettem, szerintem
mehet minden ilyesmi oda.

2017. okt. 13. du. 10:59 ezt írta ("Dani János" <notifications@github.com>):
