### ISSUE TITLE
A kormányállás helyzete szabályozható

### ISSUE THREAD

**Issue by danijanos** [SzFMV2017-Osz/AutomatedCar#60]
jobbra-balra nyíllal

**Comment by hermanistvan** [comment]
Így lenne logikus és szép, de lehet nem véletlen hogy az előző csapat is karakterekkel csinálta. A lenyomott billentyűt könnyű összehasonlítani egy charral, jobbra-balra nyílhoz nem tartozik char karakter.

**Comment by danijanos** [comment]
Szia!
Így néz ki a jobbra-balra nyíl lenyomását ellenőrző kód:
```
    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_RIGHT){
            //növeled az értéket a kormányállásnak pozitív irányban
        }
        else if (e.getKeyCode() == KeyEvent.VK_LEFT){
            //növeled az értéket a kormányállásnak negatív irányban
        }
    }
```

nem tudom, hogy az előző csapat mit és hogyan, de legfőképpen, hogy miért csinált, de szerintem ez most annyira nem fontos. Szerintem ne másoljuk azt, ami tavaly történt, max ha nagyon elakadunk valahol.

**Comment by hermanistvan** [comment]
A szóval ez már benne van a kódban.. Ezt még nem comittoltad fel? vagy csak én töltöttem le rossz verziót?

**Comment by danijanos** [comment]
még nem commitoltam azt a keretet, ahol ezt kifejtheted :)
de mindjárt kapsz egy ágat, amibe bemergelem
